# Generated by Django 4.0.5 on 2022-06-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('balance_holder', models.CharField(max_length=120, verbose_name='Орендар/Балансоутримувач')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('components', models.CharField(max_length=120, verbose_name='Складові частини')),
                ('part_size', models.CharField(max_length=120, verbose_name='Розмір частки')),
                ('area', models.CharField(max_length=120, verbose_name='Площа')),
                ('period_of_use', models.CharField(max_length=120, verbose_name='Період користування')),
                ('extra', models.CharField(blank=True, max_length=400, verbose_name='Додаткова інформація')),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': "Суб'єкт",
                'verbose_name_plural': "Суб'єкти",
            },
        ),
        migrations.CreateModel(
            name='SubjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='Зображення')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
            options={
                'verbose_name': "Зображення cуб'єкт",
                'verbose_name_plural': "Зображення cуб'єкта",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Назва')),
                ('documents', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Документи')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
            options={
                'verbose_name': "Документ cуб'єкт",
                'verbose_name_plural': "Документи cуб'єкта",
                'managed': True,
            },
        ),
    ]
