# Generated by Django 4.0.4 on 2022-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('balance_holder', models.CharField(max_length=120, verbose_name='Орендар/Балансоутримувач')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('components', models.CharField(max_length=120, verbose_name='Складові частини')),
                ('part_size', models.CharField(max_length=120, verbose_name='Розмір частки')),
                ('area', models.CharField(max_length=120, verbose_name='Площа')),
                ('period_of_use', models.CharField(max_length=120, verbose_name='Період користування')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Зображення')),
                ('documents', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/', verbose_name='Документи')),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name="Об'экт")),
            ],
        ),
    ]
