# Generated by Django 4.0.5 on 2022-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_options_topic_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AddField(
            model_name='topic',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оновлення'),
        ),
    ]
