# Generated by Django 4.0.4 on 2022-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hromady', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адреса')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('components', models.CharField(blank=True, max_length=100, verbose_name='Складові частини')),
                ('share_size', models.CharField(blank=True, max_length=100, verbose_name='Розмір частки')),
                ('total_area', models.CharField(blank=True, max_length=100, verbose_name='Загальна площа')),
                ('location', models.JSONField(blank=True, verbose_name='Місцезнаходження')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Зображення')),
                ('documents', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/', verbose_name='Документи')),
                ('hromada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hromady.communityhromady')),
            ],
            options={
                'db_table': 'objects',
                'managed': True,
            },
        ),
    ]
