# Generated by Django 4.0.4 on 2022-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHromady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_old', models.TextField()),
                ('locality', models.TextField()),
                ('type', models.TextField()),
                ('district', models.TextField()),
                ('region', models.TextField()),
                ('maps', models.TextField()),
                ('all_data', models.TextField()),
                ('all_attribute', models.TextField()),
                ('center', models.TextField()),
                ('registration', models.IntegerField()),
            ],
            options={
                'db_table': 'community_hromady',
                'managed': False,
            },
        ),
    ]
