# Generated by Django 4.0.4 on 2022-05-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHromady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('code_old', models.CharField(max_length=120)),
                ('locality', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('maps', models.TextField()),
                ('all_data', models.TextField(blank=True)),
                ('all_attribute', models.TextField(blank=True)),
                ('center', models.TextField(blank=True)),
                ('registration', models.IntegerField()),
            ],
            options={
                'db_table': 'community_hromady',
                'managed': True,
            },
        ),
    ]
