# Generated by Django 4.0.5 on 2022-06-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHromady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('code_old', models.CharField(max_length=120)),
                ('locality', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('maps', models.TextField()),
                ('all_data', models.TextField(blank=True)),
                ('all_attribute', models.TextField(blank=True)),
                ('center', models.TextField(blank=True)),
                ('registration', models.IntegerField()),
                ('flag', models.ImageField(blank=True, upload_to='', verbose_name='прапор')),
                ('emblem', models.ImageField(blank=True, upload_to='', verbose_name='Герб')),
            ],
            options={
                'verbose_name': 'Громада',
                'verbose_name_plural': 'Громади',
                'db_table': 'community_hromady',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_advertisement', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('advertisement', models.CharField(max_length=1000, verbose_name='Текст оголошення')),
                ('image_advertisement', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('community', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hromady.communityhromady', verbose_name='Громада')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'managed': True,
            },
        ),
    ]
