# Generated by Django 4.0.5 on 2022-06-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='count',
        ),
    ]
