# Generated by Django 4.0.5 on 2022-06-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hromady', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('role', models.CharField(max_length=60, verbose_name='Посада')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Номер телефону')),
                ('messenger', models.CharField(blank=True, max_length=100, verbose_name='Мессенджер')),
                ('hromada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hromady.communityhromady')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'managed': True,
            },
        ),
    ]
