# Generated by Django 4.0.5 on 2022-06-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='Роль користувача')),
            ],
            options={
                'verbose_name': 'Роль користувача',
                'verbose_name_plural': 'Ролі користувача',
            },
        ),
    ]
