# Generated by Django 4.0.5 on 2022-06-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hromady', '0001_initial'),
        ('administrator', '0002_roleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('count', models.CharField(max_length=12)),
                ('hromada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hromady.communityhromady')),
            ],
        ),
    ]
