# Generated by Django 4.0.5 on 2022-06-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hromady', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адреса')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('components', models.CharField(blank=True, max_length=100, verbose_name='Складові частини')),
                ('share_size', models.CharField(blank=True, max_length=100, verbose_name='Розмір частки')),
                ('total_area', models.CharField(blank=True, max_length=100, verbose_name='Загальна площа')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='Місцезнаходження')),
                ('extra', models.CharField(blank=True, max_length=400, verbose_name='Додаткова інформація')),
                ('hromada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hromady.communityhromady')),
            ],
            options={
                'verbose_name': "Об'єкт",
                'verbose_name_plural': "Об'єкти",
                'db_table': 'objects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='Зображення')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
            options={
                'verbose_name': "Зображення об'єкта",
                'verbose_name_plural': "Зображення об'єкта",
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Назва')),
                ('documents', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Документи')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
            options={
                'verbose_name': "Документ об'єкта",
                'verbose_name_plural': "Документи об'єкта",
                'managed': True,
            },
        ),
    ]
