from django.urls import path
from .views import *

urlpatterns = [
    path('requests', request, name='requests'),
    path('requests/success/<str:pk>', request_success, name='success'),
    path('requests/denial/<str:pk>', request_denial, name='denial'),
    path('<code>/administrator/', hromada_admin, name='admin'),
    path('<code>/administrator/users/', user_admin, name='users'),
    path('<code>/administrator/users/role/<str:pk>/', change_roll),
    path('<code>/administrator/users/update/<str:pk>/', update_user_admin, name='user_update'),
    path('<code>/administrator/users/delete/<str:pk>/', delete_user_admin, name='user_delete'),
    path('<code>/administrator/objects/', objects_admin, name='objects_admin'),
    path('<code>/administrator/object/create/', create_object_admin, name='create_object_admin'),
    path('<code>/administrator/object/update/<str:pk>/', update_object_admin, name='update_object_admin'),
    path('<code>/administrator/object/delete/<str:pk>/', delete_object_admin, name='delete_object_admin'),
    path('<code>/administrator/object/subjects/<str:pk>/', subjects_admin, name='subjects_admin'),
    path('<code>/administrator/object/subjects/create/<str:pk>', create_subject_admin, name='create_subject_admin'),
    path('<code>/administrator/object/subjects/update/<str:pk>', update_subject_admin, name='update_subject_admin'),
    path('<code>/administrator/object/subjects/delete/<str:pk>', delete_subject_admin, name='delete_subject_admin'),
    path('<code>/administrator/object/subjects/image/<str:pk>', subject_image, name='subject_image_admin'),
    path('<code>/administrator/object/subjects/create/image/<str:pk>', create_subject_image, name='create_subject_image_admin'),
    path('<code>/administrator/object/subjects/delete/image/<str:pk>', delete_subject_image),
    path('<code>/administrator/object/subjects/document/<str:pk>', subject_document, name='subject_document_admin'),
    path('<code>/administrator/object/subjects/create/document/<str:pk>', create_subject_document,
         name='create_subject_image_admin'),
    path('<code>/administrator/object/subjects/delete/document/<str:pk>', delete_subject_document),

    path('<code>/administrator/object/image/<str:pk>', object_image, name='object_image_admin'),
    path('<code>/administrator/object/create/image/<str:pk>', create_object_image,
         name='create_object_image_admin'),
    path('<code>/administrator/object/delete/image/<str:pk>', delete_object_image),
    path('<code>/administrator/object/document/<str:pk>', object_document, name='object_document_admin'),
    path('<code>/administrator/object/create/document/<str:pk>', create_object_document,
         name='create_object_image_admin'),
    path('<code>/administrator/object/delete/document/<str:pk>', delete_object_document),

    path('<code>/administrator/contacts/', contact_admin, name='contact_admin'),
    path('<code>/administrator/contacts/create/<str:pk>', create_contact_admin),
    path('<code>/administrator/contacts/update/<str:pk>', update_contact_admin),
    path('<code>/administrator/contacts/delete/<str:pk>', delete_contact_admin),
    path('<code>/administrator/update', update_image),
    path('<code>/administrator/advertisement', advertisement),
    path('<code>/administrator/advertisement/create', create_advertisement),
    path('<code>/administrator/advertisement/update/<str:pk>', update_advertisement),
    path('<code>/administrator/advertisement/delete/<str:pk>', delete_advertisement),
    # path('<code>/administrator/object/image_delete/<str:pk>', delete_object_image),
    # path('<code>/administrator/object/document_create/<str:pk>', create_object_document),
    # path('<code>/administrator/object/document_delete/<str:pk>', delete_object_document),

]
